name: opa-client test

on:
  push:
    branches: [main]

  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup podman
        run: .github/workflows/scripts/podman-setup.sh

      - name: Build
        run: cargo b --verbose

      - name: Run Tests
        run: DOCKER_SOCKET="unix:///run/user/1001/podman/podman.sock" cargo t -- --show-output
